### ISSUE TITLE
CS345 missing lecture 34

### ISSUE THREAD

**Issue by AnayMehrotra** [fat-fighter/iitk-courses#2]
Available at https://moodle.cse.iitk.ac.in/mod/resource/view.php?id=3171

**Comment by fat-fighter** [comment]
Hi, thanks for bringing this to my notice. I am not on campus and cannot access Moodle currently (too lazy to setup VPN). If you could send me the lecture, I'll add it, or I'll add it when I come back (after 2 months). Thanks again
